[build]
  functions = "./functions"
  publish = "www"

[dev]
  publish = "www"
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[redirects.headers]
  Access-Control-Allow-Origin = "*"