[build]
  base = "/"
  command = "make build"
	publish = "/www"
  functions = "/functions"

[build.environment]
  GO_IMPORT_PATH = "github.com/AdrianNueveCuatro/netlify2"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
	
[[redirects]]
  from = "/*"
  to = "/www/index.html"
  status = 200

[redirects.headers]
  Access-Control-Allow-Origin = "*"
